# Generated by Django 4.2 on 2023-06-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_image_remove_post_img_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
